package ValidadorMaterias;

public enum ListaMaterias {
    PROGRAMACION_I,
    PROGRAMACION_II,
    PROGRAMACION_III,
    LABORATORIO_I,
    LABORATORIO_II,
    LABORATORIO_III,
    LABORATORIO_IV,
    BASES_DE_DATOS,
    METODOLOGIA_DE_COMPUTACION,
    MATEMATICA_I,
    MATEMATICA_II,
    ESTADISTICA,
    INVESTIGACION_OPERATIVA
}
